name: lol_duel
dependencies:
  args: any
  logging: any
  matcher: any
  path: any
  quiver: any
  range: any
  resource: any
  trotter: any
  yaml: any
dev_dependencies:
  test: any
executables:
  duel:
