name: lol_duel
dependencies:
  path: any
  logging: any
  args: any
  yaml: any
  dragon_data:
    path: ../dragon_data
  resource: any
  trotter: any
  matcher: any
  quiver: any
dev_dependencies:
  test: any
executables:
  duel:
